version: "3"

services:
  app:
    build: .
    volumes:
      - ./output:/app/output
      - ./models:/app/models
      - ./configs:/app/user/default
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  output:
  models:
